### ISSUE TITLE
puppetlabs/reboot dependency

### ISSUE THREAD

**Issue by mzs-github** [trlinkin/puppet-domain_membership#9]
Hi,

I'm not able to install trlinkin/domain_membership with librarian-puppet since 1.1.1 when the dependency on puppetlabs/reboot >= 0.9.1 was added.

I think it's because there is no such version on the Forge. Valid versions are 0.1.0, 0.1.4, 0.1.7, 1.0.0, and 1.2.1:

http://forge.puppetlabs.com/api/v1/releases.json?module=puppetlabs/reboot

I would have thought a specification of '>= 0.9.1' would be valid, and suspect there is an underlying bug in librarian-puppet. All the same, maybe you could set the dependency to '>= 1.0.0 < 2.0.0'? That way you'll be sure a stable API version is used.

Thanks,
Mike

**Comment by trlinkin** [comment]
Hi! Sorry I haven't seen this until now. I just did a 'z' release that really only included updated docs and a working version number for this dependency. I don't know why you got that error in the first place since as you pointed out the spec I used _should_ have worked. The "bad" version was a typo I didn't notice at the time and it's about time it be updated anyway. If you have more issues, please let me know.

Thanks!
